version: "2"
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "9292:9292"
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  frontend:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      WAIT_HOSTS: api:9292
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
